name: Windows Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]

env:
  ELECTRON_CACHE: C:/electron-cache
  ELECTRON_BUILDER_CACHE: C:/electron-builder-cache

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache node modules and electron
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            flow-typed
            C:/electron-cache
            C:/electron-builder-cache
          key: windows-node-16-yarn-cache

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10.x

      - name: Install dependencies
        run: yarn --ignore-engines

      - name: Run package-ci
        run: yarn package-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint
        run: yarn lint

      - name: Run build-e2e
        run: yarn build-e2e

      - name: Archive Package
        run: |
          # Assuming your final package is in a directory named "dist" or similar
          # and you want to create a zip archive named after your repo and the build ID.
          # Adjust the paths and names as necessary.
          mkdir package
          xcopy /s /y release package
          powershell Compress-Archive -Path package -DestinationPath "${GITHUB_REPOSITORY}-${GITHUB_RUN_ID}.zip"

      # **New Step: Upload Artifact**
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${GITHUB_REPOSITORY}-${GITHUB_RUN_ID}
          path: ${GITHUB_REPOSITORY}-${GITHUB_RUN_ID}.zip
          retention-days: 1 # Optional, default is 90 days
